CREATE DATABASE IF NOT EXISTS StudentsAPI;
USE StudentsAPI;
CREATE TABLE IF NOT EXISTS Students (
  id INT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(100) NOT NULL,
  age INT NOT NULL,
  grade VARCHAR(20) NOT NULL
);
