CREATE DATABASE IF NOT EXISTS NotesAPI;
USE NotesAPI;
CREATE TABLE IF NOT EXISTS Notes (
  id INT PRIMARY KEY AUTO_INCREMENT,
  title VARCHAR(150) NOT NULL,
  content TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
