CREATE DATABASE IF NOT EXISTS ProductsAPI;
USE ProductsAPI;
CREATE TABLE IF NOT EXISTS Products (
  id INT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(120) NOT NULL,
  price DECIMAL(10,2) NOT NULL,
  stock INT NOT NULL
);
