CREATE DATABASE IF NOT EXISTS ContactsAPI;
USE ContactsAPI;
CREATE TABLE IF NOT EXISTS Contacts (
  id INT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(100) NOT NULL,
  phone VARCHAR(20) NOT NULL,
  email VARCHAR(120) NOT NULL
);
